spring:
  profiles:
    active: local

  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true # 실행 되는 SQL문을 보여 줄지 설정
      properties:
        hibernate:
          format_sql: true # 형식화된 sql 문을 보여준다. Beautifier 기능이라고 생각하면 된다
          use_sql_comments: true
#        hibernate.enable_lazy_load_no_trans: true #Lazy Load 를 적용하기 위한 설정

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml

server:
  port: 8081

---
spring:
  profiles: local

  datasource:
    db1:
      jdbcUrl: jdbc:mysql://localhost:3306/landcrawler?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: landcrawler
      password: landcrawler
